# main text of home
name: Kai Zhang
bio: Earned Not Given. / I am a fan of Technology!

# twitter summary info
description: A HomePage about My Study and Life.

picture: assets/images/picture.jpg

url: http://kkzhang0808.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
facebook: myfacebook
twitter: mytwitter
github: mygithub
email: me@jane.doe

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
